# Generated by Django 5.2.3 on 2025-08-07 04:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-is_featured', 'order', '-created_at'], 'verbose_name_plural': 'Portfolio Items'},
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='user',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='challenges',
            field=models.TextField(blank=True, help_text='Technical challenges overcome'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='demo_url',
            field=models.URLField(blank=True, help_text='Demo/Preview URL', null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='documentation_url',
            field=models.URLField(blank=True, help_text='Documentation URL', null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='duration',
            field=models.CharField(blank=True, help_text="e.g., '3 months', '2 weeks'", max_length=100),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/featured/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='gallery_images',
            field=models.TextField(blank=True, help_text='Comma-separated image URLs or paths'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub repository URL', null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Feature this project'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Show publicly'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='key_features',
            field=models.TextField(blank=True, help_text='Key features (one per line)'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='live_url',
            field=models.URLField(blank=True, help_text='Live project URL', null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of display'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_type',
            field=models.CharField(choices=[('web_app', 'Web Application'), ('mobile_app', 'Mobile Application'), ('api', 'API/Backend Service'), ('website', 'Website'), ('design', 'Design Work'), ('data_analysis', 'Data Analysis'), ('machine_learning', 'Machine Learning'), ('game', 'Game Development'), ('desktop_app', 'Desktop Application'), ('other', 'Other')], default='web_app', max_length=20),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='short_description',
            field=models.CharField(default='No Description availiable', max_length=200),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('archived', 'Archived'), ('concept', 'Concept/Planning')], default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='technologies',
            field=models.CharField(blank=True, default='', help_text='Technologies used in this portfolio item', max_length=500),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title',
            field=models.CharField(default='Untitled Portfolio Item', help_text='Title of the portfolio item', max_length=200),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='bio',
            field=models.TextField(help_text='Detailed description'),
        ),
    ]
