# Generated by Django 5.2.3 on 2025-08-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_category_options_alter_portfolio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of title', unique=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='short_description',
            field=models.CharField(help_text='Brief description for cards', max_length=300),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='technologies',
            field=models.CharField(help_text='Comma-separated technologies', max_length=500),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
