# Generated by Django 5.2.3 on 2025-08-14 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_profile_date_of_birth_profile_github_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'created_at'},
        ),
    ]
